services:
  lucky:
    image: gdy666/lucky
    container_name: lucky
    ports:
      - "${PANEL_APP_PORT_HTTP:-16601}:16601"
    volumes:
      - "${LUCKY_CONF_PATH:-./luckyconf}:/goodluck"
    restart: always 