services:
  one-hub:
    image: martialbe/one-api:v0.14.23
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    networks:
      - 1panel-network
    command: --log-dir /app/logs
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - TZ=${TZ}
      - USER_TOKEN_SECRET=${USER_TOKEN_SECRET}
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
