services:
  kspeeder:
    image: linkease/kspeeder:1.7.4
    container_name: ${CONTAINER_NAME}
    ports:
      - ${PANEL_APP_PORT_HTTP}:5003
      - ${PANEL_APP_PORT_PROXY}:5443
    volumes:
      - ./kspeeder-data:/kspeeder-data
      - ./kspeeder-config:/kspeeder-config
    restart: always
    labels:
      createdBy: Apps
