services:
  web:
    image: haedlessdev/portnote:1.2.0
    container_name: portnote
    restart: always
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    environment:
      JWT_SECRET: "changeme_jwt_secret"
      USER_SECRET: "changeme_user_secret"
      LOGIN_USERNAME: "admin"
      LOGIN_PASSWORD: "admin"
      DATABASE_URL: "postgresql://postgres:${PANEL_DB_USER_PASSWORD}@db:5432/postgres"
    depends_on:
      db:
        condition: service_started
  agent:
    image: haedlessdev/portnote-agent:1.2.0
    environment:
      DATABASE_URL: "postgresql://postgres:${PANEL_DB_USER_PASSWORD}@db:5432/postgres"
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PANEL_DB_USER_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: 